/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tasks/{task_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Task */
        post: operations["run_task_api_tasks__task_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Task */
        post: operations["generate_task_api_tasks_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dispatch */
        post: operations["dispatch_api_dispatch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monitor Snapshot */
        get: operations["monitor_snapshot_api_monitor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Live */
        get: operations["run_live_api_runs__run_id__live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/monitor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Monitor
         * @description monitor 全体の SSE。status 変化 / 新 run 出現(run_done)/ heartbeat を継続配信。
         */
        get: operations["stream_monitor_api_stream_monitor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run
         * @description 進行中 run のライブ transcript SSE。role別 stream.jsonl を tail して event/phase/end を配信。
         */
        get: operations["stream_run_api_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Run */
        post: operations["archive_run_api_runs__run_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Detail */
        get: operations["run_detail_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Evidence */
        get: operations["run_evidence_api_runs__run_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/files/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run File */
        get: operations["run_file_api_runs__run_id__files__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Transcript */
        get: operations["run_transcript_api_runs__run_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/judgment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Put Judgment */
        post: operations["put_judgment_api_runs__run_id__judgment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Message
         * @description awaiting 中の run へ続行指示を渡す。inbox.jsonl に 1 行追記し、runner が同一セッションへ注入する。
         *     指示文(中身)は人間=種類B。ここは無変換で素通すだけ。
         */
        post: operations["post_message_api_runs__run_id__message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/pr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Pr
         * @description awaiting-merge の run の PR 状態を gh で確認。マージ済みなら verdict を pass へ昇格(真の完了)。
         */
        get: operations["run_pr_api_runs__run_id__pr_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Run
         * @description 実行中/awaiting の run に停止マーカーを置く。runner が検知し `stopped` で正常終了
         *     (ロック解放・worktree 後始末・記録を残す)。awaiting は即時、実行中はターン境界で停止。
         */
        post: operations["stop_run_api_runs__run_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/pass-rate-by-skill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pass Rate By Skill */
        get: operations["pass_rate_by_skill_api_analytics_pass_rate_by_skill_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/verdict-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verdict Summary */
        get: operations["verdict_summary_api_analytics_verdict_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/gaming-suspects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gaming Suspects */
        get: operations["gaming_suspects_api_analytics_gaming_suspects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/cost-timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cost Timeline */
        get: operations["cost_timeline_api_analytics_cost_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Repos */
        get: operations["list_repos_api_repos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Detail */
        get: operations["task_detail_api_tasks__task_id__get"];
        /** Update Task */
        put: operations["update_task_api_tasks__task_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Task */
        post: operations["archive_task_api_tasks__task_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArchiveInput
         * @description アーカイブ(UI 非表示)/解除。削除はしない(ログは資産)。
         */
        ArchiveInput: {
            /**
             * Archived
             * @default true
             */
            archived: boolean;
        };
        /** CostTimelineResponse */
        CostTimelineResponse: {
            /** Generated At */
            generated_at: string;
            /** Source */
            source: string;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /** Rows */
            rows: components["schemas"]["CostTimelineRow"][];
        };
        /** CostTimelineRow */
        CostTimelineRow: {
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at?: string | null;
            /** Cost Usd */
            cost_usd?: number | null;
            /** Turns */
            turns?: number | null;
            /** Verdict */
            verdict?: string | null;
            /** Skill Sha */
            skill_sha?: string | null;
        };
        /** EvidenceFileMeta */
        EvidenceFileMeta: {
            /** Name */
            name: string;
            /** Size */
            size: number;
            /** Exists */
            exists: boolean;
        };
        /** EvidenceMeta */
        EvidenceMeta: {
            /** Files */
            files: components["schemas"]["EvidenceFileMeta"][];
        };
        /** GamingSuspectRow */
        GamingSuspectRow: {
            /** Run Id */
            run_id: string;
            /** Task */
            task?: string | null;
            /** Test Verdict */
            test_verdict?: string | null;
            /** Verifier Verdict */
            verifier_verdict?: string | null;
            /** Verifier Confidence */
            verifier_confidence?: string | null;
            /** Started At */
            started_at?: string | null;
        };
        /** GamingSuspectsResponse */
        GamingSuspectsResponse: {
            /** Generated At */
            generated_at: string;
            /** Source */
            source: string;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /** Rows */
            rows: components["schemas"]["GamingSuspectRow"][];
        };
        /** GenerateInput */
        GenerateInput: {
            /**
             * Prompt
             * @default
             */
            prompt: string;
            /**
             * Repo
             * @default
             */
            repo: string;
            /**
             * Auto Run
             * @default false
             */
            auto_run: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JudgmentInput
         * @description 判断は trust/risk/checks/learning の散文 4 キー + 任意の human_verdict。全デフォルト空文字。
         *
         *     サーバはどのフィールドにも値を合成しない。model_dump() を無変換で write_judgment へ。
         *     human_verdict は人間が verdict を覆すときだけ選ぶ構造化シグナル(空=覆さない)。
         */
        JudgmentInput: {
            /**
             * Trust
             * @default
             */
            trust: string;
            /**
             * Risk
             * @default
             */
            risk: string;
            /**
             * Checks
             * @default
             */
            checks: string;
            /**
             * Learning
             * @default
             */
            learning: string;
            /**
             * Human Verdict
             * @default
             */
            human_verdict: string;
        };
        /** LastRun */
        LastRun: {
            /** Run Id */
            run_id: string;
            /** Verdict */
            verdict?: string | null;
        };
        /** LiveRole */
        LiveRole: {
            /** Label */
            label: string;
            /** Events */
            events: {
                [key: string]: unknown;
            }[];
        };
        /** LiveSnapshot */
        LiveSnapshot: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: {
                [key: string]: unknown;
            } | null;
            /** Active */
            active: boolean;
            /** Roles */
            roles: components["schemas"]["LiveRole"][];
            /** Intervention */
            intervention?: string | null;
        };
        /** MessageInput */
        MessageInput: {
            /** Text */
            text: string;
        };
        /** MetaResponse */
        MetaResponse: {
            /** Repos */
            repos: string[];
            /** Statuses */
            statuses: string[];
            /** Judgment Fields */
            judgment_fields: string[][];
        };
        /** MonitorSnapshot */
        MonitorSnapshot: {
            /** Status */
            status: {
                [key: string]: unknown;
            } | null;
            /** Recent */
            recent: components["schemas"]["RunRow"][];
            /** Unreviewed */
            unreviewed: number;
            /** Pending */
            pending: number;
            /** Phases */
            phases: string[][];
        };
        /** PassRateResponse */
        PassRateResponse: {
            /** Generated At */
            generated_at: string;
            /** Source */
            source: string;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /** Rows */
            rows: components["schemas"]["PassRateRow"][];
        };
        /** PassRateRow */
        PassRateRow: {
            /** Skill Sha */
            skill_sha?: string | null;
            /** Pass Rate */
            pass_rate?: number | null;
            /** Avg Cost */
            avg_cost?: number | null;
            /** N */
            n?: number | null;
        };
        /** PrStatus */
        PrStatus: {
            /** Number */
            number?: number | null;
            /** Url */
            url?: string | null;
            /** State */
            state?: string | null;
            /**
             * Merged
             * @default false
             */
            merged: boolean;
            /** Ci */
            ci?: string | null;
        };
        /** ReposResponse */
        ReposResponse: {
            /** Repos */
            repos: string[];
        };
        /** RunDetail */
        RunDetail: {
            /** Run Id */
            run_id: string;
            /** Front Matter */
            front_matter: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: string;
            /** Verifier */
            verifier: {
                [key: string]: unknown;
            } | null;
            /** Judgment */
            judgment: {
                [key: string]: string;
            };
            /** Judgment Fields */
            judgment_fields: string[][];
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
        };
        /** RunListResponse */
        RunListResponse: {
            /** Runs */
            runs: components["schemas"]["RunRow"][];
            /** Verdicts */
            verdicts: string[];
        };
        /**
         * RunRow
         * @description loop.db runs 行の射影。COLUMNS と機械的に一致させる(乖離はテストで検出)。
         */
        RunRow: {
            /** Run Id */
            run_id: string;
            /** Task */
            task?: string | null;
            /** Verdict */
            verdict?: string | null;
            /** Reviewed */
            reviewed?: number | null;
            /** Repo */
            repo?: string | null;
            /** Archived */
            archived?: number | null;
            /** Started At */
            started_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** RunStartResult */
        RunStartResult: {
            /** Accepted */
            accepted: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** SummaryResponse */
        SummaryResponse: {
            /** Generated At */
            generated_at: string;
            /** Source */
            source: string;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /** Rows */
            rows: components["schemas"]["SummaryRow"][];
        };
        /** SummaryRow */
        SummaryRow: {
            /** Total Runs */
            total_runs?: number | null;
            /** Reviewed */
            reviewed?: number | null;
            /** Unreviewed */
            unreviewed?: number | null;
            /** Pass */
            pass?: number | null;
            /** Fail */
            fail?: number | null;
            /** Distinct Skills */
            distinct_skills?: number | null;
        };
        /** TaskDetail */
        TaskDetail: {
            fields: components["schemas"]["TaskFields"];
            /** Body */
            body: string;
        };
        /** TaskFields */
        TaskFields: {
            /** Task Id */
            task_id: string;
            /** Goal */
            goal: string;
            /** Repo */
            repo: string;
            /** Accept */
            accept: string[];
            /** Verify */
            verify: string;
            /** Constraints */
            constraints: string[];
            /** Allowed Tools */
            allowed_tools: string;
            /** Max Attempts */
            max_attempts: string;
            /** Status */
            status: string;
            /** Body */
            body: string;
        };
        /** TaskIdResult */
        TaskIdResult: {
            /** Task Id */
            task_id: string;
        };
        /** TaskInput */
        TaskInput: {
            /** Task Id */
            task_id?: string | null;
            /**
             * Goal
             * @default
             */
            goal: string;
            /**
             * Repo
             * @default
             */
            repo: string;
            /**
             * Accept
             * @default []
             */
            accept: string[];
            /**
             * Verify
             * @default
             */
            verify: string;
            /**
             * Constraints
             * @default []
             */
            constraints: string[];
            /**
             * Allowed Tools
             * @default
             */
            allowed_tools: string;
            /**
             * Max Attempts
             * @default
             */
            max_attempts: string;
            /**
             * Status
             * @default todo
             */
            status: string;
            /**
             * Body
             * @default
             */
            body: string;
        };
        /** TaskListResponse */
        TaskListResponse: {
            /** Tasks */
            tasks: components["schemas"]["TaskRow"][];
            /** Last */
            last: {
                [key: string]: components["schemas"]["LastRun"];
            };
            /** Running */
            running: boolean;
            /**
             * Generating
             * @default false
             */
            generating: boolean;
        };
        /** TaskRow */
        TaskRow: {
            /** Id */
            id: string;
            /** Goal */
            goal?: string | null;
            /** Status */
            status?: string | null;
            /** Repo */
            repo?: string | null;
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            last_run?: components["schemas"]["LastRun"] | null;
        } & {
            [key: string]: unknown;
        };
        /** TranscriptResponse */
        TranscriptResponse: {
            /** Events */
            events: {
                [key: string]: unknown;
            }[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerdictSummaryResponse */
        VerdictSummaryResponse: {
            /** Generated At */
            generated_at: string;
            /** Source */
            source: string;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /** Rows */
            rows: components["schemas"]["VerdictSummaryRow"][];
        };
        /** VerdictSummaryRow */
        VerdictSummaryRow: {
            /** Verdict */
            verdict?: string | null;
            /** N */
            n?: number | null;
            /** Unreviewed */
            unreviewed?: number | null;
            /** Avg Cost */
            avg_cost?: number | null;
            /** Avg Turns */
            avg_turns?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    run_task_api_tasks__task_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStartResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_task_api_tasks_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispatch_api_dispatch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStartResult"];
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    monitor_snapshot_api_monitor_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorSnapshot"];
                };
            };
        };
    };
    run_live_api_runs__run_id__live_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_monitor_api_stream_monitor_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stream_run_api_runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                verdict?: string | null;
                reviewed?: string | null;
                task?: string | null;
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_run_api_runs__run_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_detail_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_evidence_api_runs__run_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceMeta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_file_api_runs__run_id__files__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_transcript_api_runs__run_id__transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_judgment_api_runs__run_id__judgment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JudgmentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_api_runs__run_id__message_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_pr_api_runs__run_id__pr_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_run_api_runs__run_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pass_rate_by_skill_api_analytics_pass_rate_by_skill_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassRateResponse"];
                };
            };
        };
    };
    verdict_summary_api_analytics_verdict_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerdictSummaryResponse"];
                };
            };
        };
    };
    summary_api_analytics_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
        };
    };
    gaming_suspects_api_analytics_gaming_suspects_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamingSuspectsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cost_timeline_api_analytics_cost_timeline_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostTimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskIdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_repos_api_repos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReposResponse"];
                };
            };
        };
    };
    task_detail_api_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_tasks__task_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskIdResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_task_api_tasks__task_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
